version: "3.9"

services:
  db:
    image: postgres
    volumes:
       - ./data/db:/var/lib/postgresql/data
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=pass123
    ports:
       - "5432:5432"   
  web:
    build: .
    command: uvicorn stock_market_app.main:app --host 0.0.0.0 --port 8000
    volumes:
       - .:/code
    ports:
       - "8001:8000"
    depends_on:
       - db 
       
  
  redis:
    image: redis
    expose:
      - 6379
      
  worker1:
        build:
          context: .
        container_name: worsms1
        command: celery -A stock_market_app.tasks worker -l info --concurrency=8 -n worker1@%h
        environment:
            - BROKER_URL=redis://redis:6379
        depends_on:
            - redis
            - web  
            
  worker2:
        build:
          context: .
        container_name: worsms2
        command: celery -A stock_market_app.tasks worker -l info --concurrency=8 -n worker2@%h
        environment:
            - BROKER_URL=redis://redis:6379
        depends_on:
            - redis
            - web 
            
  flower:  
     image: mher/flower
     environment:
         - CELERY_BROKER_URL=redis://redis:6379/0
         - FLOWER_PORT=5555
     ports:  
        - 5555:5555
     depends_on:
        - redis
  
            

       
  
  
  
