version: "3.9"

services:
  db:
    image: postgres
    volumes:
       - ./data/db:/var/lib/postgresql/data
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=pass123
    ports:
       - "5432:5432"   
  web:
    build: .
    command: uvicorn stock_market_app.main:app --host 0.0.0.0 --port 8000
    volumes:
       - .:/code
    ports:
       - "8001:8000"
    depends_on:
       - db 
       
  
  
  
